### Q1

In [ ]:
L=[1,2,3,4,5]                # It has time complexity O(n)
sum=0
for i in L:
    sum=sum+1
print(sum)
product=1
for i in L:
    product=product*i
print(product)

### Q2

In [ ]:
for i in L:                          # It has time complexity O(n^2)
  for j in L:
    print("{},{}".format(i,j))

### Q3

In [ ]:
def intostr(i):                      # It has time complexity O(log(n))
  digit="0123456789"
  if i==0:
    return "0"
  result=" "
  while i>0:
    result=digit[i%10]+result
    i=i//10
  return result

### Q4

In [ ]:
intostr(234)                        # It has time complexity O(1)

### Q5

In [ ]:
L=[1,2,3,4,5]                        # It has time complexity O(n^2)
for i in range(len(L)):
  for j in range(i+1,len(L)):
    print("{},{}".format(i,j))

### Q6

In [ ]:
A=[1,2,3,4]                          # It has time complexity O(n^2)
B=[2,3,4,5,6]
for i in A:
  for j in B:
    if i<j:
      print("{}.{}".format(i,j))

### Q7

In [ ]:
A=[1,2,3,4]                          # It has time complexity O(n^3)
B=[2,3,4,5]
for i in A:
  for j in B:
    for k in range(10000):
      print("{},{}".format(i,j))

### Q8

In [ ]:
def factorial(n):                    # It has time complexity O(n)
  if n==1:
    return 1
  else:
    return n*factorial(n-1)

### Q9

In [ ]:
def fib(n):                          # It has time complexity O(2^n)
  if n==1 or n==0:
    return 1
  else:
    return fib(n-1)+fib(n-2)

### Q10

In [ ]:
def bubble_sort(arr):                            # It has time complexity O(n^2)
    for i in range(len(arr)-1):
        flag=0
        for j in range(len(arr)-1-i):
            if arr[j+1]<arr[j]:
                arr[j+1],arr[j]=arr[j],arr[j+1]
                flag=1
        if flag==0:
            break
    print(arr)

### Q11

In [ ]:
import random                 # It has time complexity O(n^2)
l1=[]
for i in range(1,1000):
  x=random.randint(1,1000)
  l1.append(x)

In [ ]:
l1[0:10]

[390, 468, 739, 840, 77, 478, 390, 333, 3, 156]

In [ ]:
import time
start=time.time()
bubble_sort(l1)
stop=time.time()
print(stop-start)

[2, 3, 3, 3, 4, 6, 8, 9, 9, 10, 11, 11, 11, 14, 14, 15, 15, 16, 16, 18, 19, 20, 21, 22, 23, 23, 23, 23, 26, 26, 26, 27, 27, 29, 30, 30, 34, 35, 36, 37, 38, 38, 41, 42, 42, 44, 44, 45, 46, 48, 49, 50, 50, 50, 52, 53, 53, 53, 54, 55, 55, 56, 59, 60, 62, 64, 67, 68, 68, 70, 70, 71, 71, 71, 72, 73, 74, 75, 75, 76, 77, 78, 80, 80, 82, 82, 82, 82, 84, 85, 85, 85, 88, 88, 88, 88, 89, 89, 89, 90, 92, 93, 94, 98, 98, 99, 100, 102, 102, 104, 104, 105, 105, 105, 105, 106, 107, 109, 111, 112, 113, 116, 117, 117, 118, 118, 120, 120, 121, 121, 123, 123, 124, 124, 125, 126, 128, 128, 128, 129, 130, 130, 131, 133, 133, 133, 133, 134, 134, 135, 136, 136, 140, 142, 142, 143, 145, 146, 146, 149, 150, 151, 151, 152, 156, 157, 157, 160, 160, 161, 165, 165, 166, 166, 167, 167, 169, 170, 171, 171, 172, 172, 172, 173, 174, 174, 175, 175, 175, 176, 177, 177, 178, 179, 180, 182, 182, 182, 183, 183, 184, 184, 185, 185, 186, 186, 187, 188, 189, 190, 192, 192, 193, 196, 197, 199, 202, 203, 204, 204, 204, 207, 207, 208, 208, 210, 211, 213, 213, 214, 215, 218, 219, 220, 223, 224, 226, 227, 228, 229, 229, 230, 230, 230, 231, 232, 233, 234, 235, 237, 237, 237, 238, 239, 239, 240, 242, 242, 243, 244, 247, 248, 249, 251, 252, 253, 253, 255, 257, 257, 257, 261, 261, 262, 262, 264, 264, 266, 266, 266, 268, 268, 272, 272, 273, 275, 275, 275, 275, 276, 278, 280, 280, 280, 281, 284, 284, 285, 285, 286, 286, 287, 287, 289, 289, 291, 292, 295, 296, 296, 298, 299, 301, 302, 302, 303, 303, 304, 304, 305, 306, 307, 310, 310, 311, 311, 312, 312, 314, 314, 315, 317, 317, 318, 319, 321, 322, 322, 322, 323, 323, 323, 323, 323, 326, 327, 329, 330, 331, 331, 333, 335, 335, 335, 335, 338, 339, 342, 343, 344, 345, 345, 345, 345, 347, 347, 349, 352, 352, 354, 354, 357, 357, 359, 359, 359, 359, 361, 363, 364, 365, 366, 366, 366, 367, 369, 370, 370, 371, 372, 373, 374, 374, 375, 375, 376, 376, 378, 379, 380, 383, 383, 383, 384, 384, 387, 387, 387, 387, 389, 390, 390, 391, 391, 392, 393, 395, 399, 400, 401, 401, 401, 401, 402, 404, 404, 406, 407, 407, 407, 407, 407, 408, 408, 409, 409, 410, 410, 412, 415, 418, 418, 419, 422, 423, 424, 424, 424, 425, 427, 428, 428, 432, 433, 436, 437, 437, 439, 440, 440, 441, 442, 442, 443, 443, 444, 444, 445, 446, 451, 454, 454, 454, 455, 455, 456, 458, 459, 460, 461, 462, 466, 467, 467, 467, 468, 468, 469, 473, 473, 473, 473, 476, 478, 478, 478, 479, 480, 483, 484, 484, 484, 485, 486, 487, 488, 488, 490, 490, 492, 492, 494, 495, 495, 496, 496, 498, 498, 498, 498, 499, 500, 502, 504, 505, 506, 506, 506, 506, 507, 508, 509, 509, 509, 510, 511, 512, 513, 513, 513, 514, 515, 515, 517, 518, 518, 518, 518, 529, 529, 529, 530, 531, 531, 532, 533, 533, 533, 534, 535, 535, 539, 539, 539, 540, 540, 540, 541, 541, 542, 542, 543, 543, 543, 544, 549, 550, 551, 553, 553, 554, 554, 555, 555, 556, 557, 557, 558, 558, 560, 561, 564, 564, 565, 565, 567, 569, 570, 571, 571, 574, 574, 574, 576, 576, 577, 577, 578, 585, 586, 587, 587, 587, 587, 588, 589, 590, 590, 597, 599, 600, 602, 603, 605, 606, 607, 608, 608, 609, 609, 610, 610, 610, 611, 612, 612, 613, 613, 615, 616, 617, 618, 619, 619, 620, 621, 622, 624, 625, 626, 626, 627, 628, 634, 635, 636, 637, 637, 638, 639, 639, 640, 641, 642, 642, 642, 644, 648, 648, 649, 649, 651, 652, 653, 653, 653, 653, 653, 654, 654, 655, 656, 656, 657, 658, 659, 659, 659, 662, 662, 662, 667, 667, 668, 669, 669, 669, 670, 671, 672, 672, 676, 676, 677, 677, 677, 678, 678, 678, 678, 679, 679, 680, 682, 682, 683, 683, 685, 686, 687, 687, 689, 690, 692, 692, 695, 695, 695, 696, 698, 699, 701, 702, 703, 704, 704, 706, 707, 707, 709, 712, 712, 713, 713, 715, 715, 716, 719, 719, 719, 721, 721, 722, 723, 723, 724, 725, 728, 729, 730, 731, 731, 732, 732, 732, 732, 732, 733, 733, 735, 736, 737, 738, 738, 739, 742, 744, 745, 746, 746, 747, 749, 751, 752, 753, 753, 754, 755, 757, 759, 760, 763, 764, 764, 765, 769, 770, 770, 770, 771, 771, 774, 777, 779, 780, 780, 780, 781, 781, 781, 782, 782, 783, 783, 784, 785, 785, 786, 786, 792, 792, 793, 793, 794, 794, 796, 797, 799, 799, 800, 800, 801, 802, 802, 803, 803, 804, 805, 806, 807, 810, 811, 813, 814, 814, 815, 818, 819, 820, 821, 825, 826, 830, 831, 831, 831, 833, 833, 834, 838, 840, 840, 840, 843, 845, 847, 847, 848, 848, 848, 851, 852, 852, 853, 856, 856, 860, 860, 860, 862, 863, 868, 869, 873, 876, 877, 878, 880, 881, 881, 881, 881, 882, 882, 883, 883, 885, 886, 886, 887, 890, 891, 893, 893, 894, 896, 898, 898, 899, 901, 901, 903, 903, 905, 906, 907, 907, 911, 912, 913, 913, 914, 914, 915, 915, 915, 916, 918, 918, 919, 919, 919, 920, 921, 921, 923, 925, 926, 928, 928, 929, 929, 930, 934, 934, 937, 938, 939, 939, 939, 940, 941, 941, 947, 947, 947, 948, 950, 952, 952, 954, 956, 957, 959, 961, 965, 968, 969, 970, 972, 972, 973, 975, 975, 976, 977, 977, 978, 979, 979, 980, 983, 983, 984, 984, 984, 984, 985, 988, 992, 994, 996, 996, 998, 998, 998, 999, 999, 1000]
0.05490446090698242

In [ ]:
import time
start=time.time()
bubble_sort(l1)
stop=time.time()
print(stop-start)

[2, 3, 3, 3, 4, 6, 8, 9, 9, 10, 11, 11, 11, 14, 14, 15, 15, 16, 16, 18, 19, 20, 21, 22, 23, 23, 23, 23, 26, 26, 26, 27, 27, 29, 30, 30, 34, 35, 36, 37, 38, 38, 41, 42, 42, 44, 44, 45, 46, 48, 49, 50, 50, 50, 52, 53, 53, 53, 54, 55, 55, 56, 59, 60, 62, 64, 67, 68, 68, 70, 70, 71, 71, 71, 72, 73, 74, 75, 75, 76, 77, 78, 80, 80, 82, 82, 82, 82, 84, 85, 85, 85, 88, 88, 88, 88, 89, 89, 89, 90, 92, 93, 94, 98, 98, 99, 100, 102, 102, 104, 104, 105, 105, 105, 105, 106, 107, 109, 111, 112, 113, 116, 117, 117, 118, 118, 120, 120, 121, 121, 123, 123, 124, 124, 125, 126, 128, 128, 128, 129, 130, 130, 131, 133, 133, 133, 133, 134, 134, 135, 136, 136, 140, 142, 142, 143, 145, 146, 146, 149, 150, 151, 151, 152, 156, 157, 157, 160, 160, 161, 165, 165, 166, 166, 167, 167, 169, 170, 171, 171, 172, 172, 172, 173, 174, 174, 175, 175, 175, 176, 177, 177, 178, 179, 180, 182, 182, 182, 183, 183, 184, 184, 185, 185, 186, 186, 187, 188, 189, 190, 192, 192, 193, 196, 197, 199, 202, 203, 204, 204, 204, 207, 207, 208, 208, 210, 211, 213, 213, 214, 215, 218, 219, 220, 223, 224, 226, 227, 228, 229, 229, 230, 230, 230, 231, 232, 233, 234, 235, 237, 237, 237, 238, 239, 239, 240, 242, 242, 243, 244, 247, 248, 249, 251, 252, 253, 253, 255, 257, 257, 257, 261, 261, 262, 262, 264, 264, 266, 266, 266, 268, 268, 272, 272, 273, 275, 275, 275, 275, 276, 278, 280, 280, 280, 281, 284, 284, 285, 285, 286, 286, 287, 287, 289, 289, 291, 292, 295, 296, 296, 298, 299, 301, 302, 302, 303, 303, 304, 304, 305, 306, 307, 310, 310, 311, 311, 312, 312, 314, 314, 315, 317, 317, 318, 319, 321, 322, 322, 322, 323, 323, 323, 323, 323, 326, 327, 329, 330, 331, 331, 333, 335, 335, 335, 335, 338, 339, 342, 343, 344, 345, 345, 345, 345, 347, 347, 349, 352, 352, 354, 354, 357, 357, 359, 359, 359, 359, 361, 363, 364, 365, 366, 366, 366, 367, 369, 370, 370, 371, 372, 373, 374, 374, 375, 375, 376, 376, 378, 379, 380, 383, 383, 383, 384, 384, 387, 387, 387, 387, 389, 390, 390, 391, 391, 392, 393, 395, 399, 400, 401, 401, 401, 401, 402, 404, 404, 406, 407, 407, 407, 407, 407, 408, 408, 409, 409, 410, 410, 412, 415, 418, 418, 419, 422, 423, 424, 424, 424, 425, 427, 428, 428, 432, 433, 436, 437, 437, 439, 440, 440, 441, 442, 442, 443, 443, 444, 444, 445, 446, 451, 454, 454, 454, 455, 455, 456, 458, 459, 460, 461, 462, 466, 467, 467, 467, 468, 468, 469, 473, 473, 473, 473, 476, 478, 478, 478, 479, 480, 483, 484, 484, 484, 485, 486, 487, 488, 488, 490, 490, 492, 492, 494, 495, 495, 496, 496, 498, 498, 498, 498, 499, 500, 502, 504, 505, 506, 506, 506, 506, 507, 508, 509, 509, 509, 510, 511, 512, 513, 513, 513, 514, 515, 515, 517, 518, 518, 518, 518, 529, 529, 529, 530, 531, 531, 532, 533, 533, 533, 534, 535, 535, 539, 539, 539, 540, 540, 540, 541, 541, 542, 542, 543, 543, 543, 544, 549, 550, 551, 553, 553, 554, 554, 555, 555, 556, 557, 557, 558, 558, 560, 561, 564, 564, 565, 565, 567, 569, 570, 571, 571, 574, 574, 574, 576, 576, 577, 577, 578, 585, 586, 587, 587, 587, 587, 588, 589, 590, 590, 597, 599, 600, 602, 603, 605, 606, 607, 608, 608, 609, 609, 610, 610, 610, 611, 612, 612, 613, 613, 615, 616, 617, 618, 619, 619, 620, 621, 622, 624, 625, 626, 626, 627, 628, 634, 635, 636, 637, 637, 638, 639, 639, 640, 641, 642, 642, 642, 644, 648, 648, 649, 649, 651, 652, 653, 653, 653, 653, 653, 654, 654, 655, 656, 656, 657, 658, 659, 659, 659, 662, 662, 662, 667, 667, 668, 669, 669, 669, 670, 671, 672, 672, 676, 676, 677, 677, 677, 678, 678, 678, 678, 679, 679, 680, 682, 682, 683, 683, 685, 686, 687, 687, 689, 690, 692, 692, 695, 695, 695, 696, 698, 699, 701, 702, 703, 704, 704, 706, 707, 707, 709, 712, 712, 713, 713, 715, 715, 716, 719, 719, 719, 721, 721, 722, 723, 723, 724, 725, 728, 729, 730, 731, 731, 732, 732, 732, 732, 732, 733, 733, 735, 736, 737, 738, 738, 739, 742, 744, 745, 746, 746, 747, 749, 751, 752, 753, 753, 754, 755, 757, 759, 760, 763, 764, 764, 765, 769, 770, 770, 770, 771, 771, 774, 777, 779, 780, 780, 780, 781, 781, 781, 782, 782, 783, 783, 784, 785, 785, 786, 786, 792, 792, 793, 793, 794, 794, 796, 797, 799, 799, 800, 800, 801, 802, 802, 803, 803, 804, 805, 806, 807, 810, 811, 813, 814, 814, 815, 818, 819, 820, 821, 825, 826, 830, 831, 831, 831, 833, 833, 834, 838, 840, 840, 840, 843, 845, 847, 847, 848, 848, 848, 851, 852, 852, 853, 856, 856, 860, 860, 860, 862, 863, 868, 869, 873, 876, 877, 878, 880, 881, 881, 881, 881, 882, 882, 883, 883, 885, 886, 886, 887, 890, 891, 893, 893, 894, 896, 898, 898, 899, 901, 901, 903, 903, 905, 906, 907, 907, 911, 912, 913, 913, 914, 914, 915, 915, 915, 916, 918, 918, 919, 919, 919, 920, 921, 921, 923, 925, 926, 928, 928, 929, 929, 930, 934, 934, 937, 938, 939, 939, 939, 940, 941, 941, 947, 947, 947, 948, 950, 952, 952, 954, 956, 957, 959, 961, 965, 968, 969, 970, 972, 972, 973, 975, 975, 976, 977, 977, 978, 979, 979, 980, 983, 983, 984, 984, 984, 984, 985, 988, 992, 994, 996, 996, 998, 998, 998, 999, 999, 1000]
0.0006749629974365234

In [ ]:
def buuble_sort(arr):
  for i in range(len(arr)-1):
    flag=0
    for j in range(len(arr)-1-i):
      if arr[j]>arr[j+1]:
        arr[j],arr[j+1]=arr[j+1],arr[j]
        flag=1
    if flag==0:
      break
  print(arr)
buuble_sort([5,6,3,1])

[1, 3, 5, 6]

[3, 5, 6, 10]

In [ ]:
def selection_sort(arr):
  for i in range(len(arr)-1):
    min=i
    for j in range(i+1,len(arr)):
      if arr[j]<arr[min]:
        min=j
    arr[i],arr[min]=arr[min],arr[i]
  print(arr)

In [ ]:
selection_sort([9,5,6,7,1])

In [ ]:
def binary_search(arr,item):              # It has time complexity O(log(n))
  low=0
  high=len(arr)-1
  while low<=high:
    mid=(low+high)//2
    if arr[mid]==item:
      return mid
    elif arr[mid]>item:
      high=mid-1
    elif arr[mid]<item:
      low=mid+1
  return "not found"
print(binary_search([1,2,3,4,5,6,78],100))

nit found

In [ ]:
def selection_sort(arr):
  for i in range(len(arr)-1):
    min=i
    for j in range(i+1,len(arr)):
      if arr[j]<arr[min]:
        min=j
    arr[i],arr[min]=arr[min],arr[i]
  return arr
selection_sort([7,3,5,8,9])

[3, 5, 7, 8, 9]

In [ ]:
selection_sort([7,3,5,8,9])

[3, 5, 7, 8, 9]